import Image from 'next/image'
import Head from 'next/head'
import { GetServerSideProps, NextPage } from 'next'
import { fetchCategories } from '@/http'
import { ICategory, ICollectionResponse } from '@/types'
import { AxiosResponse } from 'axios'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Next Blog</title>
        <meta
            name="description"
            content="Generated by create next app"
        />
        <link rel="icon" href="/favicon.ico" />
        </Head>
        <main>

        <p className="text-purple-400">hellp</p>
        </main>
</div>
  )
}

export const getServerSideProps: GetServerSideProps = async() => {
  //category fetch from API
  const {
    data: categories
  }: AxiosResponse<ICollectionResponse<ICategory[]>> = 
  await fetchCategories();

// console.log('categories', categories);

  return {
    props: {
        categories: {
          items: categories.data
        }
    }
  }
}

export default Home;
