import Image from 'next/image'
import Head from 'next/head'

export default function Home() {
  return (
    <div>
        <title>Next Blog</title>
        <meta
            name="description"
            content="Generated by create next app"
        />
        <link rel="icon" href="/favicon.ico" />
        <p className="text-purple-400">hellp</p>
</div>
  )
}
