import Image from 'next/image'

export default function Home() {
  return (
    <div>
        <title>Coder's Blog Homepage</title>
        <meta
            name="description"
            content="Generated by create next app"
        />
        <link rel="icon" href="/favicon.ico" />
</div>
  )
}
